# Generated by Django 2.2 on 2019-04-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
    ]
